/** @file src/lib/words.ts */
export interface Word {
	et: string;
	en: string;
}

// An expanded and categorized list of words for the Pildi Alias game.
// The English (en) version is used to search for an image.
// The Estonian (et) version is the word players must not say.
export const wordList: Word[] = [
	// Simple Objects & Nature (Good for kids)
	{ et: 'kass', en: 'cat' },
	{ et: 'koer', en: 'dog' },
	{ et: 'auto', en: 'car' },
	{ et: 'maja', en: 'house' },
	{ et: 'puu', en: 'tree' },
	{ et: 'lill', en: 'flower' },
	{ et: 'päike', en: 'sun' },
	{ et: 'kuu', en: 'moon' },
	{ et: 'täht', en: 'star' },
	{ et: 'raamat', en: 'book' },
	{ et: 'õun', en: 'apple' },
	{ et: 'pall', en: 'ball' },
	{ et: 'voodi', en: 'bed' },
	{ et: 'tool', en: 'chair' },
	{ et: 'laud', en: 'table' },
	{ et: 'uks', en: 'door' },
	{ et: 'aken', en: 'window' },
	{ et: 'leib', en: 'bread' },
	{ et: 'piim', en: 'milk' },
	{ et: 'vesi', en: 'water' },
	{ et: 'jõgi', en: 'river' },
	{ et: 'järv', en: 'lake' },
	{ et: 'meri', en: 'sea' },
	{ et: 'mets', en: 'forest' },
	{ et: 'mägi', en: 'mountain' },
	{ et: 'pilv', en: 'cloud' },
	{ et: 'vihm', en: 'rain' },
	{ et: 'lumi', en: 'snow' },

	// Animals
	{ et: 'lind', en: 'bird' },
	{ et: 'kala', en: 'fish' },
	{ et: 'elevant', en: 'elephant' },
	{ et: 'lõvi', en: 'lion' },
	{ et: 'tiiger', en: 'tiger' },
	{ et: 'jänes', en: 'rabbit' },
	{ et: 'karu', en: 'bear' },
	{ et: 'lehm', en: 'cow' },
	{ et: 'hobune', en: 'horse' },
	{ et: 'lammas', en: 'sheep' },
	{ et: 'siga', en: 'pig' },
	{ et: 'kana', en: 'chicken' },
	{ et: 'part', en: 'duck' },
	{ et: 'rebane', en: 'fox' },
	{ et: 'hunt', en: 'wolf' },
	{ et: 'siil', en: 'hedgehog' },
	{ et: 'öökull', en: 'owl' },
	{ et: 'konn', en: 'frog' },
	{ et: 'madu', en: 'snake' },
	{ et: 'liblikas', en: 'butterfly' },
	{ et: 'mesilane', en: 'bee' },
	{ et: 'ämblik', en: 'spider' },
	{ et: 'sipelgas', en: 'ant' },

	// Food & Drink
	{ et: 'banaan', en: 'banana' },
	{ et: 'apelsin', en: 'orange fruit' },
	{ et: 'pirn', en: 'pear' },
	{ et: 'maasikas', en: 'strawberry' },
	{ et: 'juust', en: 'cheese' },
	{ et: 'pizza', en: 'pizza' },
	{ et: 'burger', en: 'burger' },
	{ et: 'tort', en: 'cake' },
	{ et: 'jäätis', en: 'ice cream' },
	{ et: 'šokolaad', en: 'chocolate' },
	{ et: 'kartul', en: 'potato' },
	{ et: 'porgand', en: 'carrot' },
	{ et: 'supp', en: 'soup' },
	{ et: 'kohv', en: 'coffee' },
	{ et: 'tee', en: 'tea' },

	// Actions & Verbs
	{ et: 'jooksma', en: 'running' },
	{ et: 'ujuma', en: 'swimming' },
	{ et: 'laulma', en: 'singing' },
	{ et: 'tantsima', en: 'dancing' },
	{ et: 'magama', en: 'sleeping' },
	{ et: 'sööma', en: 'eating' },
	{ et: 'jooma', en: 'drinking' },
	{ et: 'naerma', en: 'laughing' },
	{ et: 'nutma', en: 'crying' },
	{ et: 'lendama', en: 'flying' },
	{ et: 'lugema', en: 'reading' },
	{ et: 'kirjutama', en: 'writing' },
	{ et: 'joonistama', en: 'drawing' },
	{ et: 'ehitama', en: 'building' },
	{ et: 'sõitma', en: 'driving' },

	// Concepts & Feelings
	{ et: 'armastus', en: 'love' },
	{ et: 'rõõm', en: 'joy' },
	{ et: 'kurbus', en: 'sadness' },
	{ et: 'viha', en: 'anger' },
	{ et: 'hirm', en: 'fear' },
	{ et: 'uni', en: 'dream' },
	{ et: 'sõprus', en: 'friendship' },
	{ et: 'rahu', en: 'peace' },
	{ et: 'aeg', en: 'time' },
	{ et: 'muusika', en: 'music' },
	{ et: 'vaikus', en: 'silence' },
	{ et: 'tuli', en: 'fire' },
	{ et: 'jää', en: 'ice' },

	// Places & Buildings
	{ et: 'kool', en: 'school' },
	{ et: 'pood', en: 'shop' },
	{ et: 'haigla', en: 'hospital' },
	{ et: 'raamatukogu', en: 'library' },
	{ et: 'lennujaam', en: 'airport' },
	{ et: 'raudteejaam', en: 'train station' },
	{ et: 'kirik', en: 'church' },
	{ et: 'teater', en: 'theater' },
	{ et: 'muuseum', en: 'museum' },
	{ et: 'rand', en: 'beach' },
	{ et: 'sild', en: 'bridge' },
	{ et: 'torn', en: 'tower' },

	// Technology & Transport
	{ et: 'arvuti', en: 'computer' },
	{ et: 'telefon', en: 'phone' },
	{ et: 'kaamera', en: 'camera' },
	{ et: 'televiisor', en: 'television' },
	{ et: 'raadio', en: 'radio' },
	{ et: 'lennuk', en: 'airplane' },
	{ et: 'laev', en: 'ship' },
	{ et: 'rong', en: 'train' },
	{ et: 'buss', en: 'bus' },
	{ et: 'jalgratas', en: 'bicycle' },
	{ et: 'robot', en: 'robot' },
	{ et: 'rakett', en: 'rocket' },

	// Estonian Culture (might be harder to find images for some)
	{ et: 'saun', en: 'sauna' },
	{ et: 'jaanipäev', en: 'midsummer bonfire' },
	{ et: 'kama', en: 'kama dessert' },
	{ et: 'verivorst', en: 'estonian blood sausage' },
	{ et: 'laulupidu', en: 'estonian song festival' },
	{ et: 'suitsupääsuke', en: 'barn swallow' },
	{ et: 'rukkilill', en: 'cornflower' },
	{ et: 'paekivi', en: 'limestone' },
	{ et: 'reheahi', en: 'barn kiln' },

	// Fantasy & Fun
	{ et: 'draakon', en: 'dragon' },
	{ et: 'võlur', en: 'wizard' },
	{ et: 'haldjas', en: 'fairy' },
	{ et: 'kummitus', en: 'ghost' },
	{ et: 'piraat', en: 'pirate' },
	{ et: 'aare', en: 'treasure' },
	{ et: 'loss', en: 'castle' },
	{ et: 'tulnukas', en: 'alien' },
	{ et: 'superkangelane', en: 'superhero' }
];
